# Generated by Django 5.2.4 on 2025-07-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpa_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BogieChecksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formNumber', models.CharField(max_length=50)),
                ('inspectionBy', models.CharField(max_length=50)),
                ('inspectionDate', models.DateField()),
                ('bogieDetails', models.JSONField()),
                ('bogieChecksheet', models.JSONField()),
                ('bmbcChecksheet', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='WheelSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formNumber', models.CharField(max_length=50)),
                ('submittedBy', models.CharField(max_length=100)),
                ('field', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='KPAform',
        ),
    ]
