# Generated by Django 5.2.4 on 2025-07-19 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpa_data', '0002_bogiechecksheet_wheelspecification_delete_kpaform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wheelspecification',
            old_name='field',
            new_name='fields',
        ),
        migrations.AddField(
            model_name='wheelspecification',
            name='submittedDate',
            field=models.DateField(default=datetime.date(2025, 7, 19)),
            preserve_default=False,
        ),
    ]
