# Generated by Django 5.2.4 on 2025-07-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpa_data', '0003_rename_field_wheelspecification_fields_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
