# Generated by Django 5.2.4 on 2025-07-20 17:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpa_data', '0004_submittedform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubmittedForm',
        ),
        migrations.RemoveField(
            model_name='bogiechecksheet',
            name='bmbcChecksheet',
        ),
        migrations.RemoveField(
            model_name='bogiechecksheet',
            name='bogieChecksheet',
        ),
        migrations.RemoveField(
            model_name='bogiechecksheet',
            name='bogieDetails',
        ),
        migrations.RemoveField(
            model_name='bogiechecksheet',
            name='formNumber',
        ),
        migrations.RemoveField(
            model_name='bogiechecksheet',
            name='inspectionBy',
        ),
        migrations.RemoveField(
            model_name='bogiechecksheet',
            name='inspectionDate',
        ),
        migrations.AddField(
            model_name='bogiechecksheet',
            name='adjusting_tube_screw',
            field=models.CharField(default='Not Available', max_length=100),
        ),
        migrations.AddField(
            model_name='bogiechecksheet',
            name='anchor_links',
            field=models.CharField(default='Not Available', max_length=100),
        ),
        migrations.AddField(
            model_name='bogiechecksheet',
            name='axle_guide',
            field=models.CharField(default='Not Available', max_length=100),
        ),
        migrations.AddField(
            model_name='bogiechecksheet',
            name='axle_guide_assembly',
            field=models.CharField(default='Not Available', max_length=100),
        ),
        migrations.AddField(
            model_name='bogiechecksheet',
            name='bogie_frame_condition',
            field=models.CharField(default='Not Available', max_length=100),
        ),
        migrations.AddField(
            model_name='bogiechecksheet',
            name='bogie_no',
            field=models.CharField(default='Not Available', max_length=100),
        ),
        migrations.AddField(
            model_name='bogiechecksheet',
            name='bolster',
            field=models.CharField(default='Not Available', max_length=100),
        ),
        migrations.AddField(
            model_name='bogiechecksheet',
            name='bolster_suspension_bracket',
            field=models.CharField(default='Not Available', max_length=100),
        ),
        migrations.AddField(
            model_name='bogiechecksheet',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bogiechecksheet',
            name='cylinder_body_dome_cover',
            field=models.CharField(default='Not Available', max_length=100),
        ),
        migrations.AddField(
            model_name='bogiechecksheet',
            name='date_of_ioh',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bogiechecksheet',
            name='deficit_components',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bogiechecksheet',
            name='dust_excluder',
            field=models.CharField(default='Not Available', max_length=100),
        ),
        migrations.AddField(
            model_name='bogiechecksheet',
            name='incoming_div_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bogiechecksheet',
            name='lower_spring_seat',
            field=models.CharField(default='Not Available', max_length=100),
        ),
        migrations.AddField(
            model_name='bogiechecksheet',
            name='maker_year_built',
            field=models.CharField(default='Not Available', max_length=100),
        ),
        migrations.AddField(
            model_name='bogiechecksheet',
            name='pawl_pawl_spring',
            field=models.CharField(default='Not Available', max_length=100),
        ),
        migrations.AddField(
            model_name='bogiechecksheet',
            name='piston_trunnion_body',
            field=models.CharField(default='Not Available', max_length=100),
        ),
        migrations.AddField(
            model_name='bogiechecksheet',
            name='plunger_spring',
            field=models.CharField(default='Not Available', max_length=100),
        ),
        migrations.AddField(
            model_name='bogiechecksheet',
            name='protective_tubes',
            field=models.CharField(default='Not Available', max_length=100),
        ),
        migrations.AddField(
            model_name='bogiechecksheet',
            name='side_bearer',
            field=models.CharField(default='Not Available', max_length=100),
        ),
        migrations.AddField(
            model_name='bogiechecksheet',
            name='tee_bolt_hex_nut',
            field=models.CharField(default='Not Available', max_length=100),
        ),
    ]
