# Generated by Django 5.2.4 on 2025-07-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpa_data', '0005_delete_submittedform_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wheelspecification',
            name='fields',
        ),
        migrations.RemoveField(
            model_name='wheelspecification',
            name='formNumber',
        ),
        migrations.RemoveField(
            model_name='wheelspecification',
            name='submittedBy',
        ),
        migrations.RemoveField(
            model_name='wheelspecification',
            name='submittedDate',
        ),
        migrations.AddField(
            model_name='wheelspecification',
            name='condemning_dia',
            field=models.CharField(default='Not Available', max_length=100),
        ),
        migrations.AddField(
            model_name='wheelspecification',
            name='last_shop_issue',
            field=models.CharField(default='Not Available', max_length=100),
        ),
        migrations.AddField(
            model_name='wheelspecification',
            name='tread_diameter',
            field=models.CharField(default='Not Available', max_length=100),
        ),
        migrations.AddField(
            model_name='wheelspecification',
            name='wheel_gauge',
            field=models.CharField(default='Not Available', max_length=100),
        ),
    ]
