# Generated by Django 5.2.4 on 2025-07-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpa_data', '0006_remove_wheelspecification_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheelspecification',
            name='axle_box_housing_bore_dia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wheelspecification',
            name='wheel_disc_width',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wheelspecification',
            name='condemning_dia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wheelspecification',
            name='last_shop_issue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wheelspecification',
            name='tread_diameter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wheelspecification',
            name='wheel_gauge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
