# Generated by Django 5.2.4 on 2025-07-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpa_data', '0007_wheelspecification_axle_box_housing_bore_dia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheelspecification',
            name='bearing_seat_diameter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wheelspecification',
            name='intermediate_wwp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wheelspecification',
            name='roller_bearing_bore_dia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wheelspecification',
            name='roller_bearing_outer_dia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wheelspecification',
            name='roller_bearing_width',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
