# Generated by Django 5.2.4 on 2025-07-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpa_data', '0008_wheelspecification_bearing_seat_diameter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bogiechecksheet',
            name='date_of_ioh',
            field=models.DateField(blank=True, null=True),
        ),
    ]
