# Generated by Django 5.2.4 on 2025-07-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpa_data', '0009_alter_bogiechecksheet_date_of_ioh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bogiechecksheet',
            name='adjusting_tube_screw',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bogiechecksheet',
            name='anchor_links',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bogiechecksheet',
            name='axle_guide',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bogiechecksheet',
            name='axle_guide_assembly',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bogiechecksheet',
            name='bogie_frame_condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bogiechecksheet',
            name='bogie_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bogiechecksheet',
            name='bolster',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bogiechecksheet',
            name='bolster_suspension_bracket',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bogiechecksheet',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bogiechecksheet',
            name='cylinder_body_dome_cover',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bogiechecksheet',
            name='dust_excluder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bogiechecksheet',
            name='incoming_div_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bogiechecksheet',
            name='lower_spring_seat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bogiechecksheet',
            name='maker_year_built',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bogiechecksheet',
            name='pawl_pawl_spring',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bogiechecksheet',
            name='piston_trunnion_body',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bogiechecksheet',
            name='plunger_spring',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bogiechecksheet',
            name='protective_tubes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bogiechecksheet',
            name='side_bearer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bogiechecksheet',
            name='tee_bolt_hex_nut',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
